//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityBuilder.Res.String {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnityBuilder.Res.String.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   *.cpp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CppFile_wild {
            get {
                return ResourceManager.GetString("CppFile_wild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .cpp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CppFileExtension {
            get {
                return ResourceManager.GetString("CppFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   exist dir {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExistsDirectory {
            get {
                return ResourceManager.GetString("ExistsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   exist {0}{1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExistsFile {
            get {
                return ResourceManager.GetString("ExistsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *.h과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HeaderFile_wild {
            get {
                return ResourceManager.GetString("HeaderFile_wild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .h과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HeaderFileExtension {
            get {
                return ResourceManager.GetString("HeaderFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ======과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainSection {
            get {
                return ResourceManager.GetString("MainSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   =========================================과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainSectionEnd {
            get {
                return ResourceManager.GetString("MainSectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   not exist dir {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoExistsDirectory {
            get {
                return ResourceManager.GetString("NoExistsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   not exist dir {0}, Create Dir {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoExistsDirectory_Create {
            get {
                return ResourceManager.GetString("NoExistsDirectory_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   not exist {0}{1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoExistsFile {
            get {
                return ResourceManager.GetString("NoExistsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   not exist {0}{1}, Create {0}{1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoExistsFile_Create {
            get {
                return ResourceManager.GetString("NoExistsFile_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1} {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SectionForm {
            get {
                return ResourceManager.GetString("SectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ----과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SubSection1 {
            get {
                return ResourceManager.GetString("SubSection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SubSection2 {
            get {
                return ResourceManager.GetString("SubSection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   \t{0} {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextForm {
            get {
                return ResourceManager.GetString("TextForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextLine {
            get {
                return ResourceManager.GetString("TextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnityBuild\과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnityBuildDirectoryName {
            get {
                return ResourceManager.GetString("UnityBuildDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UnityBuild과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnityBuildFileName {
            get {
                return ResourceManager.GetString("UnityBuildFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last.ver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VersionRelativeFile {
            get {
                return ResourceManager.GetString("VersionRelativeFile", resourceCulture);
            }
        }
    }
}
